In [121]:
import numpy as np

### Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [69]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
x = zp
y = ks
n = 10

In [70]:
B1 = (n*np.sum(x * y) - np.sum(x) * np.sum(y)) / (n * np.sum(x ** 2) - np.sum(x) ** 2)
B1

2.6205388824027653

In [71]:
B0 = np.mean(y) - B1 * np.mean(x)
B0

444.17735732435955

In [80]:
X = x.reshape(n, 1)
X

array([[ 35],
       [ 45],
       [190],
       [200],
       [ 40],
       [ 70],
       [ 54],
       [150],
       [120],
       [110]])

In [81]:
y1 = y.reshape(n, 1)
y1

array([[401],
       [574],
       [874],
       [919],
       [459],
       [739],
       [653],
       [902],
       [746],
       [832]])

In [82]:
B1 = np.dot(np.linalg.inv(np.dot(X.T, X)), X.T @ y)
B1

array([5.88982042])

### Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [60]:
def mse_(B1, x, y, n=10):
    return np.sum((B1 * x - y) ** 2) / n

In [61]:
x = zp
y = ks
alpha = 1e-6
B1 = 0.1
n = 10

In [62]:
for i in range(501):
    B1 -= alpha * (2 / n) * np.sum((B1 * x - y) * x)
    if i % 50 == 0:
        print('Internation = {i}, B1 = {B1}, mse = {mse}'.format(i=i, B1=B1, mse=mse_(B1, x, y)))

Internation = 0, B1 = 0.25952808, mse = 493237.7212546963
Internation = 50, B1 = 4.497229618367758, mse = 83233.94472982832
Internation = 100, B1 = 5.54537842245223, mse = 58151.31823171113
Internation = 150, B1 = 5.804626485478126, mse = 56616.849068093856
Internation = 200, B1 = 5.868748638669329, mse = 56522.97550129376
Internation = 250, B1 = 5.884608547059329, mse = 56517.232638059555
Internation = 300, B1 = 5.888531320728348, mse = 56516.88130936019
Internation = 350, B1 = 5.889501575592372, mse = 56516.85981627392
Internation = 400, B1 = 5.8897415574471985, mse = 56516.85850140053
Internation = 450, B1 = 5.889800914315978, mse = 56516.858420961085
Internation = 500, B1 = 5.889815595583751, mse = 56516.858416040064


In [55]:
y_pred2 = B1 * zp
y_pred2

array([ 206.1437147 ,  265.04191891, 1119.06587982, 1177.96408403,
        235.59281681,  412.28742941,  318.05030269,  883.47306302,
        706.77845042,  647.88024621])

### Произвести вычисления как в пункте 2, но с вычислением intercept. Учесть, что изменение коэффициентов должно производиться на каждом шаге одновременно (то есть изменение одного коэффициента не должно влиять на изменение другого во время одной итерации).

In [122]:
def mse_(B0, B1, x, y, n=10):
    return np.sum((B0 + B1 * x - y) ** 2) / n

In [131]:
x = zp
y = ks
alpha = 3e-5
B0 = 0.1
B1 = 0.1
n = 10

In [ ]:
for i in range(1000001):
    y_pred3 = B0 + B1 * x
    B0 -= alpha * (2 / n) * np.sum((y_pred3 - y))
    B1 -= alpha * (2 / n) * np.sum((y_pred3 - y) * x)
    if i % 100000 == 0:
        print('Internation = {i}, B0 = {B0}, B1 = {B1}, mse = {mse}'.format(i=i, B0 = B0, B1=B1, mse=mse_(B0, B1, x, y)))