Задачи 1 и 2
Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Случайная величина X задаёт число правильных ответов при простом угадывании. Найдите математическое ожидание данной случайной величины. Найдите дисперсию случайной величины X.

Подсказка: постройте закон распределения случайной величины X.

In [44]:
import numpy as np

In [45]:
a = 5 # колличество вопросов
b = 4 # колличество вариантов ответа в вопросе

In [46]:
x_values = np.arange(0, 6)
print(x_values) # варианты колличества правильных ответов

[0 1 2 3 4 5]


In [47]:
x_probabilities = (1 / b) ** x_values * (3 / b) ** (a - x_values)
x_probabilities[:10] # закон распределения случайной величины X.

array([0.23730469, 0.07910156, 0.02636719, 0.00878906, 0.00292969,
       0.00097656])

In [48]:
m = (x_values * x_probabilities).sum()
m # математическое ожидание

0.1748046875

In [49]:
y_values = x_values - m
print(y_values)

[-0.17480469  0.82519531  1.82519531  2.82519531  3.82519531  4.82519531]


In [50]:
z_values = y_values ** 2
print(z_values)

[ 0.03055668  0.6809473   3.33133793  7.98172855 14.63211918 23.2825098 ]


In [51]:
d = (z_values * x_probabilities).sum()
print(d) # дисперсию случайной величины X

0.28470952436327934


Пользователь получает в среднем 10 писем со спамом на свой почтовый ящик за сутки. Найти число N, такое, что с вероятностью 0.95 пользователь получит не более N писем со спамом за текущий день.

In [85]:
def poisson_proba(k: int, lambda_: float) -> float:
    """Формула Пуассона.
    """
    
    return (lambda_ ** k) * (np.exp(-lambda_)) / np.math.factorial(k)
w = 0.95 # интересующая нас вероятность
lambda_ = 10 # среднее колличество писем со спамом в сутки
while sum(poisson_proba(k=i, lambda_=lambda_) for i in range(16)) <= w:
    k+=1
print (k)

12


Производятся выстрелы по мишени. Вероятность попадания в мишень при одном выстреле равна 0.01. Сколько выстрелов нужно сделать чтобы быть уверенным с вероятностью 0.9, что хотя бы 6 раз будет совершено попадание?

Подсказка: 1) "Вероятность попасть k раз при n выстрелах" - на какое распределение это похоже? 2) А если нам нужна вероятность P(X >= k), а не P(X = k)? 3) Здесь предстоит немножко покодить.